version: "3.2"
services:
  elasticsearch:
    image: perplexedgamer/elastic-savi:latest
    deploy:
      placement:
        constraints:
          - node.labels.role == monitor
    networks:
      net:
  kibana:
    image: perplexedgamer/kibana-savi:latest
    volumes:
      - /home/ubuntu/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - /home/ubuntu/certs/elasticsearch_certificate.pem:/home/elasticsearch_certificate.pem
    deploy:
      placement:
        constraints:
          - node.labels.role == monitor
    extra_hosts: 
      - "elasticsearch:10.12.0.23"
    networks:
      net:
  nginx:
    image: perplexedgamer/savi-nginx:v2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/config/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/config/.htpasswd:/etc/nginx/.htpasswd
      - /home/ubuntu/certs/elasticsearch_certificate.pem:/etc/nginx/elasticsearch_certificate.pem
      - /home/ubuntu/certs/elasticsearch_private_key.pem:/etc/nginx/elasticsearch_private_key.pem
      - /home/ubuntu/certs/kibana_certificate.pem:/home/kibana_certificate.pem
      - /home/ubuntu/certs/kibana_private_key.pem:/home/kibana_private_key.pem
    deploy:
      placement:
        constraints:
          - node.labels.role == monitor
    ports:
      -  target: 9200 
         published: 9200
         protocol: tcp
         mode: host   
      -  target: 5601 
         published: 5601
         protocol: tcp
         mode: host   
    #ports:
    #  - 9200:9200
    #  - 5601:5601
    networks:
      net:
networks:
  net:
    driver: overlay 
    ipam:
      config:
        - subnet: 174.17.0.0/24
