version: '3.1'

services:
   v2:
     image: perplexedgamer/elascale_secure:latest
     volumes:
       - /home/ubuntu/Elascale_secure/config:/Elascale_secure/config
       - /home/ubuntu/Elascale_secure/certs:/Elascale_secure/certs
     deploy:
       placement:
         constraints:
           - node.labels.role == master
     environment:
       PYTHONUNBUFFERED :   "0"
       PKEY_PASSWORD : /run/secrets/pkey_password
       PKEY_FILE : /run/secrets/pkey_file
     extra_hosts: 
       - "elasticsearch:10.2.1.17"
     secrets:
       - pkey_password
       - pkey_file
secrets:
  pkey_password:
    file: /home/ubuntu/Elascale_secure/pass_key/pass_key_passphrase.txt
  pkey_file:
    file: /home/ubuntu/Elascale_secure/pass_key/pass_key
