version: "3"
services:
  elasticsearch:
    image: perplexedgamer/elastic-savi:latest
    deploy:
      placement:
        constraints:
          - node.labels.role == monitor
    networks:
      net:
  kibana:
    image: perplexedgamer/kibana-savi:latest
    volumes:
      - /home/ubuntu/Elascale_secure/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - /home/ubuntu/Elascale_secure/certs/elasticsearch_certificate.pem:/home/elasticsearch_certificate.pem
    deploy:
      placement:
        constraints:
          - node.labels.role == monitor
    extra_hosts: 
      - "elasticsearch:10.11.1.24"
    networks:
      net:
  nginx:
    image: savi-nginx_v5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/Elascale_secure/config/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/Elascale_secure/config/.htpasswd:/etc/nginx/.htpasswd
      - /home/ubuntu/Elascale_secure/certs/elasticsearch_certificate.pem:/etc/nginx/elasticsearch_certificate.pem
      - /home/ubuntu/Elascale_secure/certs/elasticsearch_private_key.pem:/etc/nginx/elasticsearch_private_key.pem
      - /home/ubuntu/Elascale_secure/certs/kibana_certificate.pem:/home/kibana_certificate.pem
      - /home/ubuntu/Elascale_secure/certs/kibana_private_key.pem:/home/kibana_private_key.pem
    deploy:
      placement:
        constraints:
          - node.labels.role == monitor
    ports:
      - 9200:9200
      - 5601:5601
    networks:
      net:
networks:
  net:
    driver: overlay 
    ipam:
      config:
        - subnet: 174.17.0.0/24
