version: '3.2'

services:
   secure:
     image: perplexedgamer/elascale_secure:v2
     volumes:
       - /home/ubuntu/Elascale_secure/config:/Elascale_secure/config
       - /home/ubuntu/Elascale_secure/certs:/Elascale_secure/certs
       - /home/ubuntu/Elascale_secure/config/engine_config.py:/Elascale_secure/mape/engine_config.py
     deploy:
       placement:
         constraints:
           - node.labels.role == master
     environment:
       PYTHONUNBUFFERED :   "0"
     extra_hosts: 
       - "elasticsearch:10.6.1.3"
     secrets:
       - pkey_password
       - pkey_file
   ui:
     image: perplexedgamer/ui:v6
     volumes:
       - /home/ubuntu/Elascale_secure/config:/home/ubuntu/Elascale_secure/config
       - /home/ubuntu/Elascale_secure/certs:/home/ubuntu/Elascale_secure/certs
       - /var/run/docker.sock:/var/run/docker.sock
     deploy:
       placement:
         constraints:
           - node.labels.role == master
     ports:
       -  target: 8888 
          published: 8888
          protocol: tcp
          mode: host  
     #ports:
     #  - 8888:8888
     environment:
       HOST_IP : "10.2.1.12"
       HOST_PORT : "8888"
       ELASTIC_IP : "10.6.1.3"
       MICRO : "/home/ubuntu/Elascale_secure/config/microservices.ini"
       MACRO : "/home/ubuntu/Elascale_secure/config/macroservices.ini"
       SELF_CERT : "/home/ubuntu/Elascale_secure/certs/elascale_ui_certificate.pem"
       SELF_KEY : "/home/ubuntu/Elascale_secure/certs/elascale_ui_private_key.pem"
       NGINX_CERT : "/home/ubuntu/Elascale_secure/certs/elasticsearch_certificate.pem"
       USERNAME : "elascale"
       PASSWORD : "savi_elascale"
       PYTHONUNBUFFERED : "1"
     extra_hosts: 
       - "elasticsearch:10.6.1.3"
secrets:
  pkey_password:
    file: /home/ubuntu/Elascale_secure/pass_key/pass_key_passphrase.txt
  pkey_file:
    file: /home/ubuntu/Elascale_secure/pass_key/pass_key
